# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HIFUAnimalMonitorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(240, 10, 121, 51))
        self.connectButton.setObjectName("connectButton")
        self.monitorControlLabel = QtWidgets.QLabel(self.centralwidget)
        self.monitorControlLabel.setGeometry(QtCore.QRect(20, 10, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.monitorControlLabel.setFont(font)
        self.monitorControlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monitorControlLabel.setObjectName("monitorControlLabel")
        self.disconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectButton.setGeometry(QtCore.QRect(380, 10, 121, 51))
        self.disconnectButton.setObjectName("disconnectButton")
        self.pingButton = QtWidgets.QPushButton(self.centralwidget)
        self.pingButton.setGeometry(QtCore.QRect(520, 10, 121, 51))
        self.pingButton.setObjectName("pingButton")
        self.temperatureDisplay = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.temperatureDisplay.setGeometry(QtCore.QRect(10, 100, 521, 311))
        self.temperatureDisplay.setObjectName("temperatureDisplay")
        self.temperatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.temperatureLabel.setGeometry(QtCore.QRect(130, 60, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.heartbeatLabel = QtWidgets.QLabel(self.centralwidget)
        self.heartbeatLabel.setGeometry(QtCore.QRect(140, 420, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.heartbeatLabel.setFont(font)
        self.heartbeatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.heartbeatLabel.setObjectName("heartbeatLabel")
        self.heartbeatDisplay = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.heartbeatDisplay.setGeometry(QtCore.QRect(10, 460, 521, 311))
        self.heartbeatDisplay.setObjectName("heartbeatDisplay")
        self.temperatureInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.temperatureInput.setGeometry(QtCore.QRect(650, 200, 241, 81))
        self.temperatureInput.setObjectName("temperatureInput")
        self.setButton = QtWidgets.QPushButton(self.centralwidget)
        self.setButton.setGeometry(QtCore.QRect(710, 300, 121, 51))
        self.setButton.setObjectName("setButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(670, 10, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(820, 10, 104, 51))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.monitorControlLabel.setText(_translate("MainWindow", "Monitor Controls"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.pingButton.setText(_translate("MainWindow", "Ping"))
        self.temperatureLabel.setText(_translate("MainWindow", "Temperature Reading"))
        self.heartbeatLabel.setText(_translate("MainWindow", "Heartbeat Reading"))
        self.setButton.setText(_translate("MainWindow", "Set"))
        self.statusLabel.setText(_translate("MainWindow", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
